### ISSUE TITLE
Improve status API performance #2

### ISSUE THREAD

**Issue by jbornemann** [TWCable/grabbit#101]
If needed, lets improve status API further. Some potential things to address : 

1.) Rebalance the var/grabbit tree. Currently above recommended JCR tree level maximums. 
2.) Restructure var/grabbit tree so that schema is more reflective of how we access status data
3.) Clear out var/grabbit tree after some period of time?

**Comment by jbornemann** [comment]
@jdigger @sagarsane per our discussions. Feel free to add more detail

**Comment by jdigger** [comment]
Did GH-107 cover most of this?

**Comment by jbornemann** [comment]
Yeah, i'll close
