### ISSUE TITLE
Add ability to apply delete-before-write to entire config file w/option for exception paths

### ISSUE THREAD

**Issue by kharied** [TWCable/grabbit#103]
Understanding is that currently the delete-before-write flag can only be applied on a path-by-path basis to grabbit config paths. 
Would like an enhancement where the delete-before-write flag could be 
1. applied to the entire config file.
2. support exceptions.
So, basically, could say delete-before-write all paths in this file EXCEPT this list. 

Example:
###delete-before-write-all
path: '/content/twc'
path: '/content/dam'

###db4write exception paths
path: '/content/twc/en/protectedContent'

**Comment by cffried** [comment]
example beginning of a file (yaml)
# Information for connecting to the source content
clientNodeType : 'author'
serverUsername : 'admin'
serverPassword : 'admin'
serverHost : 'omega-content-auth01.nce.webapps.rr.com'
serverPort : 4502

deltaContent : true # default for all the paths
deleteBeforeWrite:  true 

pathConfigurations :
    -   path: '/content/twc'
        deleteBeforeWrite: false
        excludePaths:
            - 'en/businessuat'
            - 'en/uat-test-pages-resp'
            - 'business-home/UAT'

**Comment by jdigger** [comment]
+1

**Comment by pgoodrich** [comment]
@jdigger Looks like this issue can be closed

**Comment by jdigger** [comment]
Thanks, @pgoodrich
