### ISSUE TITLE
Issue with Grabbit (grabbit-3.0.5) installation

### ISSUE THREAD

**Issue by ani91** [TWCable/grabbit#104]

**Comment by jbornemann** [comment]
Hi @ani91 !

Sorry you are having issues! A couple of things : 

- Double-check the path "/CQt5/author/crx-quickstart/Grabbit/grabbit-3.0.5/config.json." grabbit.sh is expecting an absolute path to a configuration file. e.g on Linux : /data/apps/cq5/myconfig.json
- You mentioned you uploaded the protobuf compiler to your Linux servers. It sounds like you are building from source? Note that the protobuf compiler is only required at compile-time. Did everything get installed to your CQ5 servers as expected?
- Aside from the configuration not being uploaded, I see that you received a 409 Conflict response. Check to make sure you can reach the target server, and that Grabbit is running by checking "http://t5-author.fcc.ca:4502/grabbit/job/all.json"

If none of these points help, could you provide a the version of CQ/AEM you are running?

**Comment by jbornemann** [comment]
Also, note that exclude paths are relative. For e.g, path: "apps/onlinePresence/i18n", excludePaths: ["fr"]

**Comment by ani91** [comment]
Hi@jbornemann ,

Sorry for late reply.

- I have checked the path of config.json file and it is the absolute path.

- I followed this link during installation of Grabbit (_**https://github.com/TWCable/grabbit/**_ ) where it is mentioned that we need installation of ProtoBuf as prerequisite but I am unable to understand what is the use of this protobuff. Only I have run ./configure and the output is attached herewith.
[config.txt](https://github.com/TWCable/grabbit/files/128449/config.txt)

- As per your third suggestion I hit the your given url (http://t5-author.fcc.ca:4502/grabbit/job/all.json) but it was redirecting to error page. Snapshot is attached.
![capture](https://cloud.githubusercontent.com/assets/16403426/13016761/80463452-d19f-11e5-8614-59ad93f0ad73.JPG)

- It would be better if you guide me step by step what needs to be done for installation of this Grabbit tool.

Thanks 
Anirban Paria

**Comment by ani91** [comment]
One more thing I have missed out that we are using AEM 5.6 version.

**Comment by jbornemann** [comment]
Hmm, okay. From your original post, one issue is that for some reason grabbit.sh (which is really just a wrapper around cURL) can't find, and/or access your "config.json." Make sure you have appropriate read permissions using stat, or ls -l; You may try toying around with curl -X GET --data-binary "@\<absolute_path_to_file\>" --verbose to debug the issue. Another issue may be that Grabbit isn't installed, based on your screenshot above. 

To make things a little bit easier - I noticed that we didn't provide a built version of 3.0.5; I've uploaded the built AEM package to https://github.com/TWCable/grabbit/releases/download/v3.0.5/grabbit-3.0.5.zip

The protobuf compiler is only required if you are building Grabbit from source. 

- Try downloading the built software from the link above and installing it to both source, and destination servers via the Package Manager. 
- After you've done that, check to make sure all your bundles are in the "Started" state via /system/console on both servers
- If your bundles are good, try /grabbit/jobs/all.json again on both servers. For a fresh install, you should see a response of "[]"
- If you see the "[]", try running ./grabbit.sh with your configuration again. If you still run into issues, if you would attach your client log from the source server "<aem_home>/logs/batch-client.log", and your server log from the destination server "<aem_home>/logs/batch-client.log"; this will help.

**Comment by jbornemann** [comment]
Also, this may be unclear in the documentation (which we should fix), but the path to the configuration that grabbit.sh asks for is an absolute path **on the machine you are running grabbit.sh** not an absolute path on the machine the Grabbit client is running - although of course, the machine may be the same.

**Comment by jdigger** [comment]
@ani91 Did @jbornemann's clarifications help?

**Comment by ani91** [comment]
@jdigger 

Sorry for the late reply! .I have engaged with a lot of work. I have followed the instructions but no hope. Sharing the screenshots for your help.

![image](https://cloud.githubusercontent.com/assets/16403426/13233064/bc675580-d990-11e5-9fb1-3d4701decf68.png)

![image](https://cloud.githubusercontent.com/assets/16403426/13233139/0a235292-d991-11e5-963f-235b92f17c67.png)

![image](https://cloud.githubusercontent.com/assets/16403426/13233901/d21937dc-d994-11e5-8877-f17f3f96db1c.png)

Also not found any logs in the said path /CQt1/author/crx-quickstart/logs.

**Comment by jbornemann** [comment]
@ani91 are all the bundles (including Grabbit) in a "Started" state? If you ssh into the box you are playing with above, does curl -u \<username\>:\<password\> localhost:4502/grabbit/job/all.json return '[]', with SC_OK?

You can't find the batch-client.log, or batch-server.log? Is Grabbit printing any messages to your error.log on start up?

**Comment by jbornemann** [comment]
Hey @ani91 did you get this resolved?
