### ISSUE TITLE
Problem with groovy-all during installation

### ISSUE THREAD

**Issue by myslinskipawel** [TWCable/grabbit#105]
There is a major problem with installation Grabbit-5.0.0 on server with active groovy-all bundle. It causes OSGI crash (Felix is not responding). After restart many jars from Grabbit package can't be activated

Test path:
1. Get clean AEM6.1 instance
2. Install aem-groovy-console-7.0.1.zip
3. Install Sun-Misc-Fragment-Bundle-1.0.0.zip
4. Restart instance
5. Install Grabbit-5.0.0.zip
6. Check if Felix Console is working
[error.log.txt](https://github.com/TWCable/grabbit/files/188164/error.log.txt)

Installing Grabbit-5.0.0.zip without groovy-all-2.3.6.jar solves the problem.

**Comment by jdigger** [comment]
Haven't looked at what version of Groovy that aem-groovy-console-7.0.1.zip installs, but I suspect there's a conflict created between it and Grabbit. In either case, it increases the value of GH-59.

**Comment by jdigger** [comment]
Closing this, but bumping up the priority of GH-59.
