### ISSUE TITLE
version support

### ISSUE THREAD

**Issue by fschroder** [TWCable/grabbit#109]
Hi,
Does this project support copying of /jcr:system/jcr:versionStorage? Have you tried?
Note that the only tool (besides full backups) that seems to support this is https://docs.adobe.com/docs/en/aem/6-1/deploy/upgrade/using-crx2oak.html#Version%20Support
For example vlt rcp doesn't support it, and generating a package with this data will fail to install with a "javax.jcr.nodetype.ConstraintViolationException: Item is protected" error.

**Comment by sagarsane** [comment]
Hey @fschroder, 

Grabbit does not support copying `/jcr:system/jcr:versionStorage`. As far as I know as well, only the crx2oak tool supports copying JCR Version nodes as far as content migration is concerned.

**Comment by fschroder** [comment]
I suspected so.
Thanks a lot for the quick answer!

**Comment by sagarsane** [comment]
Okay thanks for checking @fschroder!
