### ISSUE TITLE
Allow passing the batch size as part of job configuration

### ISSUE THREAD

**Issue by jdigger** [TWCable/grabbit#112]
It's currently [hard coded at 1,000 nodes in DefaultClientService](https://github.com/TWCable/grabbit/blob/fdba912/grabbit/src/main/groovy/com/twcable/grabbit/client/services/impl/DefaultClientService.groovy#L42)

The appropriate batch size can vary dramatically, whether it's thousands of tiny nodes or a few massive nodes. Should allow passing the batch size in as a configuration of the job/path.

**Comment by jdigger** [comment]
It looks like it may also be set in `grabbit/src/main/resources/META-INF.spring/client-batch-job.xml`. This should be consolidated (or at least better documented) as part of this.

**Comment by jbornemann** [comment]
I think we can close this one right @jdigger ? Reopen if I am wrong
