### ISSUE TITLE
Windows compatability

### ISSUE THREAD

**Issue by timdonovanuk** [TWCable/grabbit#119]
There is no grabbit.bat file and the included .sh does not execute well in Cygwin. Looking at the .sh file all it seems to do is execute a curl command, also leaving me unclear what all the Grabbit files are actually for. 

Looks great, just no idea how to make it run without switching environments.

**Comment by jbornemann** [comment]
Yes, that's correct. It's a simple launcher script that allows one to get up-and-going, and interacting with a a server that has Grabbit installed quickly; Essentially a wrapper around cURL, and the Grabbit REST interface like you said.

Did you have specific problem(s) that you ran into when using Cygwin? I don't think we have had much Windows coverage as of late in that area.

You may look into https://github.com/TWCable/grabbit-cli , or just using cURL directly...

**Comment by jdigger** [comment]
Specifically, https://github.com/TWCable/grabbit-cli/pull/10 (waiting on some final code-review) should make running on Windows (no Cygwin or curl) easy. [This comment talks about how to build and run](https://github.com/TWCable/grabbit-cli/pull/10#issuecomment-229171037).

**Comment by jdigger** [comment]
[The stand-alone Grabbit CLI](https://github.com/TWCable/grabbit-cli) is now released, with no dependencies (including OS) other than a Java 8 runtime.

**Comment by timdonovanuk** [comment]
Thanks, I checked it out and its now infinitely easier to run on Win targets! Cheers

**Comment by jdigger** [comment]
Thanks for the confirmation. "In theory" it was supposed to work on Windows, but I didn't have a Windows machine to test it on. Glad to know it works in reality. 😎 :shipit:
