### ISSUE TITLE
Build and install on remote instances

### ISSUE THREAD

**Issue by kexsteve** [TWCable/grabbit#121]
I am wondering if there is a way I can build the code locally and install on some other connected instances instead of the default localhost with 4502/4503 port, e.g. qa.grabbit.com:45120, 10.22.3.411:4503, when running "gradlew clean build install refreshAllBundles". Thanks.

**Comment by jdigger** [comment]
There are a number of ways, but why are you building it instead of using the pre-built binaries on https://bintray.com/twcable/aem/Grabbit ? Are you making modifications?

**Comment by kexsteve** [comment]
Thanks, it makes sense to install the pre-build binaries.
