### ISSUE TITLE
Grabbit with cq5.5

### ISSUE THREAD

**Issue by abogit** [TWCable/grabbit#123]
Any chance to get grabbit to work with 5.5?

**Comment by jdigger** [comment]
Unfortunately, it is unlikely that any of the core committers will actively work on that, for the pragmatic reason that we we use AEM 6.1 and are looking at moving to 6.2. We don't have any instances of 5.5 to even develop/test against.

That said, part of the beauty of open-source is that you can customize it to your needs. Most of the back-porting is likely simply aligning the package/bundle dependencies. I don't recall any API changes we needed to make, but that should be fairly minimal.

So please fork this and make whatever changes you need. If you'd like to share it with everyone else (including having it come into this codebase for us to help maintain), please send us a pull-request and we'll be happy to help give direction on questions you may have.

**Comment by abogit** [comment]
Thanks Jim for the response.  I will take a look at the code but we are under pressure to get a 5.5 instance upgraded so don’t have too much time.
We will be utilizing grabbit to move content between environments once we get the upgrade completed.

**Comment by jdigger** [comment]
Closing this ticket, though if you have a pull-request we'll be happy to help you on it.
