### ISSUE TITLE
Packages to be installed for grabbit setup

### ISSUE THREAD

**Issue by akiranmutnuru** [TWCable/grabbit#131]
I am using AEM 5.6 and Grabbit 3.0.5

There are many paths as below which are to be sync'ed from one repository to another
/apps/i18n
/apps/abcd-ie/i18n
/apps/abcd-sso-ie/i18n
/apps/xyz-ie/i18n
/etc/globalvariables

My Query is:
As per the instructions, i have installed below packages on both the repositories
1) grabbit.zip
2) Sun-Misc-Fragment-Bundle-1.0.0.zip  
Is it enough to copy above mentioned paths from one repository to another??????

i understood that, these packages are enough for only content sync 
but in order to copy the above mentioned paths, Do I need any extra packages to be installed on repositories??????
Please help me. Thanks a million.

**Comment by akiranmutnuru** [comment]
Few more paths as mentioned above
/etc/stepplan
/etc/designs/abcd/components
/apps/abcd/i18n/sk
/etc/tags
/etc/stepplan
/apps/abcd/i18n
/etc/lists

**Comment by jdigger** [comment]
After installing those packages on the client (receiver) and server (source) machines, you start the copy jobs by making some REST calls to the client. See [Running docs](../blob/master/docs/Running.adoc) and [the stand-alone CLI](../../grabbit-cli) for more information.

**Comment by akiranmutnuru** [comment]
I understood that. and I did it already.
My Question is:
Do i have to install any extra packages in order to copy the code in the above mentioned paths???

**Comment by jdigger** [comment]
I assume you meant "copy the **_content_** in the above mention paths". If not, I'm afraid I have no idea what you're trying to say.

`grabbit.zip` and `Sun-Misc-Fragment-Bundle-1.0.0.zip` are the only packages you need. To copy content from one server to another, you create copy job configuration files, per the directions referenced above. They are sent to the client, and the job configurations have the paths, server connection information, etc.

**Comment by akiranmutnuru** [comment]
Actually, the above mentioned paths contains some jar files. (some code related stuff)
but NOT content files like (images/pdfs/videos)
Actually, i heard from SagarSane some time back that, some extra packages are required in case if we copy the code related stuff.

i really dont know whether i heard correctly or whether i understand it correctly.
please clarify and through some light on it

My only concern is, when i use Grabbit tool, there should not be any harm to the existing environment.
That is why i am asking all the queries in detail.
Sorry to bother you.

**Comment by jdigger** [comment]
Grabbit is just moving bytes around, and as far as the JCR is concerned, content is content, regardless of whether its jars, jsps, pngs, etc. While the protocols and the like are very different, as far as the JCR is concerned you can think of it very much like vault, with Node transactionality, etc.

On the server, reading the nodes is just a read operation. And of course the nodes that you are explicitly writing on the client (using essentially the same JCR APIs as vault). Otherwise the only writing that Grabbit does is to `/var/grabbit` to keep track of its jobs.

I'll let @SagarSane comment if he wants of "extra packages", but hopefully all of that makes sense, @akiranmutnuru.

**Comment by sagarsane** [comment]
That's right. @akiranmutnuru you don't need any more Grabbit packages to move over code. But of-course if you are unsure, I would suggest testing the code copy using Grabbit on you local or something to make sure everything goes alright 😄

**Comment by akiranmutnuru** [comment]
Thank you so much @sagarsane and @jdigger
