### ISSUE TITLE
Grabbit won't start in AEM 6.2 -- Joda-Time dependency not found

### ISSUE THREAD

**Issue by sagarsane** [TWCable/grabbit#139]
See #138 for more details.

Looks like Joda Time dependency version needs to change (to 2.9.1) for Grabbit to work in AEM 6.2.

**Comment by thedoc31** [comment]
Sagar, any idea how long this will take to fix?

**Comment by jdigger** [comment]
PR #140 has been opened. Mostly needs testing.

**Comment by sagarsane** [comment]
Fixed by #140
