### ISSUE TITLE
HTTPS sync

### ISSUE THREAD

**Issue by jonekdahl** [TWCable/grabbit#149]
The Grabbit sample config files specifies `serverHost` and `serverPort`. Our AEM instances are running https ports, so I would like to know if it is possible to tell Grabbit to use https instead of http.

**Comment by jonekdahl** [comment]
As I haven't found any configuration option to use https, I'm guessing it is currently not possible to do this with Grabbit. I think it would be a useful addition since passwords otherwise are unprotected.

**Comment by jbornemann** [comment]
@jonekdahl thanks for the ticket! This would be a good improvement.

**Comment by jonekdahl** [comment]
@jbornemann If I could get some pointers on how to best implement this feature I could have a go at it.

**Comment by jbornemann** [comment]
Hey @jonekdahl! Thanks! We would really appreciate the help!

 Some things to look at : 

- com.twcable.grabbit.client.batch.steps.http.CreateHttpConnectionTasklet. I think all that is needed here is to burn in the server connection scheme in buildURIForRequest(). We could probably get the server scheme from configuration, much like we do for host, port, etc.

- For configuration, you can look at com.twcable.grabbit.GrabbitConfiguration. This is used to build the Grabbit configuration from our client JSON/YAML files. The configuration object is then used to build a client batch job. You might have a look at com.twcable.grabbit.client.batch.ClientBatchJob.ServerBuilder

- grabbit.sh might have some problems using cURL with SSL for unverified certs they way it is now. We may choose to add a -k flag or something? 

That's all I can think of now. Do let us know if you have further questions!

**Comment by jonekdahl** [comment]
PR created: #154
