### ISSUE TITLE
Non-interactive mode in grabbit.sh

### ISSUE THREAD

**Issue by jonekdahl** [TWCable/grabbit#151]
It would be great if the `grabbit.sh` script could be run in non-interactive mode. We are planning on using Grabbit to perform scheduled content syncing, and a non-interactive mode would simplify the automation.

**Comment by jdigger** [comment]
That shell script is really meant for illustrative purposes. The much more full-featured CLI is https://github.com/TWCable/grabbit-cli

Does that serve your purposes?

**Comment by jonekdahl** [comment]
Ah, it didn't occur to me to look for another repository. Thanks for the pointer, I will give grabbit-cli a go.
