### ISSUE TITLE
Information Needed

### ISSUE THREAD

**Issue by akiranmutnuru** [TWCable/grabbit#159]
1) is there any feature added on newer versions of grabbit to exclude regex-style paths ?
2) is there any possibility in the newer versions of Grabbit to process the ASSETS which are more than 64 MB ?

please share the information 
Thanks a million :-)

**Comment by jbornemann** [comment]
Hey @akiranmutnuru 

1.) This isn't a feature that's been implemented. Feel free to open a feature request detailing what the feature would look like, and what it would accomplish!

2.) I assume you mean *only* process assets over 64MB? We don't place any size restrictions on content. Variations on this idea have been tossed around. Some sort of general filtering mechanism would be nice. I don't think anyone has thought it completely through at this point regarding what it would look like; or at least documented it in a feature request.

**Comment by jbornemann** [comment]
@akiranmutnuru does this answer your questions sufficiently? 

Just to keep things organized, I'm going to close this ticket; but if you need more clarification, feel free to reopen it!
