### ISSUE TITLE
Status of 404 when attempting to create a connection

### ISSUE THREAD

**Issue by abogit** [TWCable/grabbit#160]
I am attempting to migrate a small test folder from a 5.6.1 instance to a 6.2 instance.  The grabbit bundle (7.0.2) is active on the 6.2 instance.   The grabbit bundle (3.0.5) is active on the 5.6.1. instance.  

The contents of my configuration file: 
{
  "serverUsername" : "admin",
  "serverPassword" : "xxxxxxx",
  "serverHost" : "cq5authdev",
  "serverPort" : "4502",
  "batchsize" : 150,
  "deltaContent" : true,
  "pathConfigurations" :  [
      {
          "path" : "/content/newsletter",
          "batchSize" : 50
      }
   ]
}
 
I initiated grabbit.sh on the 5.6.1 machine and entered the client host:port, username and password.  I then gave the absolute path to the configuration file.  Logging on both sides has been set to TRACE for the client and server classes through configMgr.  No batch log is available on the server side.  

Here is the relative output in the batch log on the client side.

10.11.2016 15:55:47.510 *DEBUG* [clientJobLauncherTaskExecutor-5] com.twcable.grabbit.client.batch.steps.validation.ValidJobDecider com.twcable.grabbit.client.batch.stes.validation.ValidJobDecider Job determined to be valid for job path /content/newsletter
10.11.2016 15:55:47.540 *INFO* [clientJobLauncherTaskExecutor-5] com.twcable.grabbit.client.batch.steps.workflows.WorkflowOffTasklet WorkflowConfig :
10.11.2016 15:55:47.540 *INFO* [clientJobLauncherTaskExecutor-5] com.twcable.grabbit.client.batch.steps.workflows.WorkflowOffTasklet Nothing to process...
10.11.2016 15:55:47.557 *INFO* [clientJobLauncherTaskExecutor-5] com.twcable.grabbit.client.batch.steps.workspace.DeleteBeforeWriteDecider Will retain nodes under job pth for 3327737590083677799...
10.11.2016 15:55:48.426 *WARN* [clientJobLauncherTaskExecutor-5] com.twcable.grabbit.client.batch.steps.http.CreateHttpConnectionTasklet Received a status of 404 when atempting to create a connection to cq5authdev. Bailing out. See debug log for more details.
10.11.2016 15:55:48.426 *DEBUG* [clientJobLauncherTaskExecutor-5] com.twcable.grabbit.client.batch.steps.http.CreateHttpConnectionTasklet Request to start a connection ith cq5authdev resulted in: org.apache.http.conn.BasicManagedEntity@1ae12d8e.
10.11.2016 15:55:48.464 *INFO* [clientJobLauncherTaskExecutor-5] com.twcable.grabbit.client.batch.ClientBatchJobExecutionListener Cleanup : JobExecution: id=332773759003677799, version=1, startTime=Thu Nov 10 15:55:47 CST 2016, endTime=Thu Nov 10 15:55:48 CST 2016, lastUpdated=Thu Nov 10 15:55:47 CST 2016, status=FAILED, exitStatus=extCode=FAILED;exitDescription=, job=[JobInstance: id=8, version=0, Job=[clientJob]], jobParameters=[{serverPassword=xxxxxx, deleteBeforeWrite=false, scheme=http, por=4502, transactionID=3268690561561351109, clientUsername=admin, excludePaths=, workflowConfigIds=, batchSize=50, timestamp=1478814947465, serverUsername=admin, host=cq5uthdev, pathDeltaContent=true, path=/content/newsletter}] . Job Complete. Releasing session, and input stream
10.11.2016 15:55:48.464 *INFO* [clientJobLauncherTaskExecutor-5] com.twcable.grabbit.client.batch.ClientBatchJobExecutionListener Grab from cq5authdev for Current Path content/newsletter took : 979 milliseconds

Any suggestions on what I have done wrong?  There is no network related reason that the two machines would not be able to establish a connection.

**Comment by abogit** [comment]
I forgot to mention that when I query the status of the provided jobId the response is python: module json.tool not found.

**Comment by jbornemann** [comment]
Hello @abogit, Grabbit 3 and Grabbit 7 are not compatible, which is why you are encountering this error. Syncing instances across major Grabbit versions is not supported. Although not officially supported/vetted, you may be able to install 3.0.5 on both of your instances, as is being done in https://github.com/TWCable/grabbit/issues/156

**Comment by jbornemann** [comment]
Sorry, I missed the 2nd comment. Make sure you have at least Python 2.6 installed.

**Comment by jbornemann** [comment]
Hey @abogit I am going to close this one out. Please reopen if you have further questions down the road.

**Comment by abogit** [comment]
Sounds good  - thanks
