### ISSUE TITLE
Pull Content form CQ5.6 to AEM6.2

### ISSUE THREAD

**Issue by simageye** [TWCable/grabbit#162]
Is it possible to pull Content from CQ5.6 into the AEM6.2?
When it is possible, which grabbit version has to be installed on CQ5.6 and
which grabbit version has to be installed on AEM6.2.
Are there special settings to do within the grabbit configurations on the System?

I successfully pulled from CQ5.6 to CQ5.6 and from AEM6.2 to AEM6.2.

**Comment by RJHend** [comment]
That would be great.  I hope you get a resounding yes on you question.  I've been messing around with it for a few days now and have yet to get it running on 5.6.1 at all.  6.2 seems to accept jobs but they all fail, and the logs show no detail (even in trace).  Anyway, hoping that it is possible.  Would love to start with a fresh repo, and not have to 'migrate'.

**Comment by jbornemann** [comment]
Hey @simageye @RJHend!

Maybe, and no. Grabbit's protocol can only "talk" to another Grabbit of the same major version, and if you look at [AEM Support](https://github.com/TWCable/grabbit/blob/master/docs/AEMSupport.adoc) you will notice that no major version of Grabbit supports both AEM 6.2, and CQ 5.6. That said, I have heard via https://github.com/TWCable/grabbit/issues/156 that there might be some success in installing 3.0.5 on AEM 6.2. When I tried, incompatible versions of Joda Time prevented Grabbit's installation, so dscirto might have had to mess around with things. That said, 3.0.5 on AEM6.2 is certainly relatively uncharted territory. 

Other than that, for particular nodes between 5.6, and AEM 6.x (mostly DAM related), you will run into node definition incompatibilities. Grabbit is a sync tool, and does not provide AEM migration capability. Bonafide migration tools such as crx2oak, or Package Manager will handle these nodes. 

If you get beyond those two hurdles, Grabbit should still be able to help you.

**Comment by simageye** [comment]
Thanks for all this fast answers. We decided to use the standard replication agent which uses the "durbo" protocol. We are record the stream from CQ5.6 to a file and when the replication is finished, we are playing it to AEM6.2. So far, we are not manipulating the stream for filter actions.

I am closing the thread now as "will not be solved".
