### ISSUE TITLE
com.google.protobuf.InvalidProtocolBufferException

### ISSUE THREAD

**Issue by sansai2011** [TWCable/grabbit#175]
Hi The following error i am getting please help me to resolve

Status for JobId [all] is :
[
    {
        "endTime": "2017-02-24T05:52:03+0000",
        "exitStatus": {
            "exitCode": "FAILED",
            "exitDescription": "",
            "running": false
        },
        "jcrNodesWritten": -1,
        "jobExecutionId": 9103514274687328229,
        "path": "/content/dam/manipal/mgait",
        "startTime": "2017-02-24T05:52:02+0000",
        "timeTaken": 538
    },
    {
        "endTime": "2017-02-24T05:52:03+0000",
        "exitStatus": {
            "exitCode": "FAILED",
            "exitDescription": "",
            "running": false
        },
        "jcrNodesWritten": -1,
        "jobExecutionId": 4009305053639159105,
        "path": "/content/mgait",
        "startTime": "2017-02-24T05:52:02+0000",
        "timeTaken": 521
    }
]

org.springframework.batch.core.step.AbstractStep Encountered an error executing step clientNamespaceSync in job clientJob com.google.protobuf.InvalidProtocolBufferException: **While parsing a protocol message, the input ended unexpectedly in the middle of a field.**  This could mean either than the input has been truncated or that an embedded message misreported its own length.

Thanks in Advance.

**Comment by sagarsane** [comment]
Hi @sansai2011 -- can you please elaborate on your setup?

1. What AEM versions are you using?
2. What Grabbit versions (on both the client and server) are you using?
3. Is Grabbit correctly installed? (Are all bundles active on Grabbit Client and Grabbit Server + is `/grabbit/job/all.json` returning an empty array for you?)

The most possible issue with this is that Grabbit is not correctly installed on your AEM instances.

**Comment by sansai2011** [comment]
Hi Sagar,

Thanks for replying, Yes, your comment was correct it wasn't installed correctly.
Now its working correctly, but the problem is the whole tree is not getting syncing
Getting following exception

25.02.2017 11:14:56.091 *ERROR* [clientJobLauncherTaskExecutor-3] org.springframework.batch.core.step.AbstractStep Encountered an error executing step clientJcrNodes in job clientJob javax.jcr.RepositoryException: **Invalid last path element for adding node lpAdminProperties_2017_02_02-06_33[2] relative to node /content/mgait/lp/product-management/jcr:content/RFI_ Admin_Backup**
	at org.apache.jackrabbit.core.session.AddNodeOperation.perform(AddNodeOperation.java:72)
	at org.apache.jackrabbit.core.session.AddNodeOperation.perform(AddNodeOperation.java:37)
	at org.apache.jackrabbit.core.session.SessionState.perform(SessionState.java:216)
	at org.apache.jackrabbit.core.ItemImpl.perform(ItemImpl.java:91)
	at org.apache.jackrabbit.core.NodeImpl.addNodeWithUuid(NodeImpl.java:1814)
	at org.apache.jackrabbit.core.NodeImpl.addNode(NodeImpl.java:1774)
	at org.apache.jackrabbit.commons.JcrUtils.getOrCreateByPath(JcrUtils.java:1136)
	at org.apache.jackrabbit.commons.JcrUtils.getOrCreateByPath(JcrUtils.java:1016)
	at org.apache.jackrabbit.commons.JcrUtils.getOrCreateByPath(JcrUtils.java:909)
	at com.twcable.grabbit.jcr.ProtoNodeDecorator.getOrCreateNode(ProtoNodeDecorator.groovy:85)
	at com.twcable.grabbit.jcr.ProtoNodeDecorator.writeToJcr(ProtoNodeDecorator.groovy:65)
	at com.twcable.grabbit.client.batch.steps.jcrnodes.JcrNodesWriter.writeToJcr(JcrNodesWriter.groovy:88)
	at com.twcable.grabbit.client.batch.steps.jcrnodes.JcrNodesWriter.write(JcrNodesWriter.groovy:71)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.writeItems(SimpleChunkProcessor.java:175)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.doWrite(SimpleChunkProcessor.java:151)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.write(SimpleChunkProcessor.java:274)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:199)
	at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:75)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:395)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:267)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:77)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:368)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:253)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:195)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:141)
	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:64)
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:60)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:151)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:130)
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:135)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:301)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:134)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)



Since,  in crx/de having replica(duplicate) of nodes(Please refer attachment)- Check excepton mentioned from above in bold

![crx-de](https://cloud.githubusercontent.com/assets/25974445/23328679/ed22ff78-fb4d-11e6-806d-6e7cc7f35a33.png)

Configuration file is- Correct me if something wrong. if in such case i want to sync these nodes also.

{
  "serverUsername" : "admin",
  "serverPassword" : "admin",
  "serverScheme" : "http",
  "serverHost" : "172.24.3.21",
  "serverPort" : "4502",
  "batchSize" : 150,
  "deltaContent" : false,
  "pathConfigurations" :  [
    {
      "path" : "/content/mgait",
      "batchSize" : 50
    }
  ]
}

**Comment by sagarsane** [comment]
Hey @sansai2011 - thanks for the update. What AEM version are you working with?

Looking at your screenshot and the error, the file name in there is illegal (specifcally the `[` and `]` characters). Please check [this reference](https://docs.adobe.com/content/docs/en/spec/jcr/2.0/3_Repository_Model.html#3.2.4%20Naming%20Restrictions) for more information. That's what the JCR API Grabbit uses is failing (legitimately) and throwing the RepositoryException. 

I am not sure how that node name got in there in the first place, but it's likely that some of the older CQ versions allowed that node name to get in.

Having said that, it could be argued that Grabbit should be able to manage this gracefully -- which it certainly doesn't right now. Please take a look at #114 and #124 for more information. The best Grabbit could do is to [escape the illegal JCR characters](https://wiki.apache.org/jackrabbit/EncodingAndEscaping) (`[` and `]`) but that would still not write the node name like it is in the source (in your case, ending with `[2]`) but write it something like `%5B2%5D`, so I don't think that will help you either. It is also non-trivial general, since for example `:` in `jcr:content` node should not go through the escaping and is allowed by JCR.

Of course the quickest workaround for this would be to rename the source node name to remove the illegal characters. Though I don't know how many more are there in the AEM instance you are working with.

Question: If you try to use the Package Manager to package up and install that node on another instance, does it work?

**Comment by jbornemann** [comment]
Unfortunately, @sagarsane's comment still stands. We can't write illegal JCR characters like [, or ] because the underlying node API, and specification won't allow it. The package manager uses a different mechanism that bends some of these rules.

**Comment by sansai2011** [comment]
Thanks @ jbornemann

ohhh.....!!!


Which Grabbit version is good for AEM 5.6.1.
Let me know what will be workaround to achieve this.

2. How to use the API to clean the job repository?

Thanks.

**Comment by jbornemann** [comment]
CQ5.6 can use up to Grabbit 3.0.5 as detailed 

https://github.com/TWCable/grabbit/blob/master/docs/AEMSupport.adoc

To clean the repository, see 

https://github.com/TWCable/grabbit/blob/master/docs/Cleaning.adoc

An example would be : 

`curl -u admin:admin -v -X POST localhost:4502/grabbit/jobrepository/clean?hours=1
`

to clean all jobs older than an hour

**Comment by sansai2011** [comment]
Hi @jbornemann

I am not able to clear the repository please find the below error.

Enter jobID to access status of a job, "all" to access all jobs, or "b" to go back
curl -u admin:admin -v -X POST localhost:4502/grabbit/jobrepository/clean?hours=1
* STATE: INIT => CONNECT handle 0x6000578c0; line 1413 (connection #-5000)
* Added connection 0. The cache now contains 1 members
*   Trying ::1...
* TCP_NODELAY set
* STATE: CONNECT => WAITCONNECT handle 0x6000578c0; line 1466 (connection #0)
* Connected to localhost (::1) port 4502 (#0)
* STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x6000578c0; line 1583 (connection #0)
* Marked for [keep alive]: HTTP default
* STATE: SENDPROTOCONNECT => DO handle 0x6000578c0; line 1601 (connection #0)
* Server auth using Basic with user 'admin'
> POST /grabbit/job/curl HTTP/1.1
> Host: localhost:4502
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.52.1
> Accept: */*
>
* STATE: DO => DO_DONE handle 0x6000578c0; line 1680 (connection #0)
* STATE: DO_DONE => WAITPERFORM handle 0x6000578c0; line 1807 (connection #0)
* STATE: WAITPERFORM => PERFORM handle 0x6000578c0; line 1817 (connection #0)
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 201 Created
< Connection: Keep-Alive
* Server Day-Servlet-Engine/4.1.52 is not blacklisted
< Server: Day-Servlet-Engine/4.1.52
< Content-Type: text/html;charset=UTF-8
< Date: Tue, 28 Feb 2017 16:51:45 GMT
< Transfer-Encoding: chunked
< Location: /grabbit/job/curl
< Set-Cookie: cq-authoring-mode=CLASSIC; Path=/
<
{ [1377 bytes data]
* STATE: PERFORM => DONE handle 0x6000578c0; line 1981 (connection #0)
* multi_done
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
* Expire cleared
* STATE: INIT => CONNECT handle 0x6000578c0; line 1413 (connection #-5000)
* Found bundle for host localhost: 0x60006cdc0 [can pipeline]
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (::1) port 4502 (#0)
* STATE: CONNECT => DO handle 0x6000578c0; line 1459 (connection #0)
* Server auth using Basic with user 'admin'
> POST /grabbit/jobrepository/clean?hours=1.json HTTP/1.1
> Host: localhost:4502
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.52.1
> Accept: */*
>
* STATE: DO => DO_DONE handle 0x6000578c0; line 1680 (connection #0)
* STATE: DO_DONE => WAITPERFORM handle 0x6000578c0; line 1807 (connection #0)
* STATE: WAITPERFORM => PERFORM handle 0x6000578c0; line 1817 (connection #0)
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 200 OK
< Connection: Keep-Alive
* Server Day-Servlet-Engine/4.1.52 is not blacklisted
< Server: Day-Servlet-Engine/4.1.52
< Content-Type: text/html;charset=UTF-8
< Date: Tue, 28 Feb 2017 16:51:46 GMT
< Transfer-Encoding: chunked
< Set-Cookie: cq-authoring-mode=CLASSIC; Path=/
<
{ [1488 bytes data]
* STATE: PERFORM => DONE handle 0x6000578c0; line 1981 (connection #0)
* multi_done
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact

Status for JobId [curl -u admin:admin -v -X POST localhost:4502/grabbit/jobrepository/clean?hours=1] is :
No JSON object could be decoded
Enter jobID to access status of a job, "all" to access all jobs, or "b" to go back

**Comment by jbornemann** [comment]
`curl -u admin:admin -v -X POST localhost:4502/grabbit/jobrepository/clean?hours=1`

is a command you run. It's not input to grabbit.sh. Create a new tab or window on your shell, and run the command above.

**Comment by sansai2011** [comment]
Yes the same command i have executed on new window but not clearing the repository.
still showing in /var/grabbit/job/repository

FYI
santoshs@MTL-IT-SAI ~
$ curl -u admin:admin -v -X POST localhost:4502/grabbit/jobrepository/clean?hours=1
* STATE: INIT => CONNECT handle 0x6000578c0; line 1413 (connection #-5000)
* Added connection 0. The cache now contains 1 members
*   Trying ::1...
* TCP_NODELAY set
* STATE: CONNECT => WAITCONNECT handle 0x6000578c0; line 1466 (connection #0)
* Connected to localhost (::1) port 4502 (#0)
* STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x6000578c0; line 1583 (connection #0)
* Marked for [keep alive]: HTTP default
* STATE: SENDPROTOCONNECT => DO handle 0x6000578c0; line 1601 (connection #0)
* Server auth using Basic with user 'admin'
> POST /grabbit/jobrepository/clean?hours=1 HTTP/1.1
> Host: localhost:4502
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.52.1
> Accept: */*
>
* STATE: DO => DO_DONE handle 0x6000578c0; line 1680 (connection #0)
* STATE: DO_DONE => WAITPERFORM handle 0x6000578c0; line 1807 (connection #0)
* STATE: WAITPERFORM => PERFORM handle 0x6000578c0; line 1817 (connection #0)
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 200 OK
< Connection: Keep-Alive
* Server Day-Servlet-Engine/4.1.52 is not blacklisted
< Server: Day-Servlet-Engine/4.1.52
< Content-Type: text/html;charset=UTF-8
< Date: Wed, 01 Mar 2017 11:21:09 GMT
< Transfer-Encoding: chunked
< Set-Cookie: cq-authoring-mode=CLASSIC; Path=/
<
<html>
<head>
    <title>Content modified /grabbit/jobrepository/clean</title>
</head>
    <body>
    <h1>Content modified /grabbit/jobrepository/clean</h1>
    <table>
        <tbody>
            <tr>
                <td>Status</td>
                <td><div id="Status">200</div></td>
            </tr>
            <tr>
                <td>Message</td>
                <td><div id="Message">OK</div></td>
            </tr>
            <tr>
                <td>Location</td>
                <td><a href="/grabbit/jobrepository/clean" id="Location">/grabbit/jobrepository/clean</a></td>
            </tr>
            <tr>
                <td>Parent Location</td>
                <td><a href="/grabbit/jobrepository" id="ParentLocation">/grabbit/jobrepository</a></td>
            </tr>
            <tr>
                <td>Path</td>
                <td><div id="Path">/grabbit/jobrepository/clean</div></td>
            </tr>
            <tr>
                <td>Referer</td>
                <td><a href="" id="Referer"></a></td>
            </tr>
            <tr>
                <td>ChangeLog</td>
                <td><div id="ChangeLog">&lt;pre&gt;modified("/grabbit/jobrepository/clean/hours");&lt;br/&gt;&lt;/pre&gt;</div></td>
            </tr>
        </tbody>
    </table>
    <p><a href="">Go Back</a></p>
    <p><a href="/grabbit/jobrepository/clean">Modified Resource</a></p>
    <p><a href="/grabbit/jobrepository">Parent of Modified Resource</a></p>
    </body>
* STATE: PERFORM => DONE handle 0x6000578c0; line 1981 (connection #0)
* multi_done
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
* Expire cleared
</html>

**Comment by jbornemann** [comment]
@sansai2011 , oh I see. You are using 3.0.5. The clean functionality was added in Grabbit 5.

**Comment by sansai2011** [comment]
So how can i achieve to clean repository instead doing manually?

**Comment by jbornemann** [comment]
You can create a PR to backport the changes to the 3.x line, or you can clean the repository manually by deleting nodes under /var/grabbit.

**Comment by jbornemann** [comment]
If you have the experience, you can use Git to apply the clean repository commits on-top of the 3.0.5 commit; and open up a new PR comparing against the 3.0.5 commit. Once you test it, and it is vetted, we would create a 3.1.0 release. 

If you aren't a developer, and are comfortable with this stuff; I would recommend just cleaning the repository manually.

**Comment by sansai2011** [comment]
Ohhhh... I am not a developer,in this case can i create PR to achieve this?

**Comment by jbornemann** [comment]
I would recommend having one of your engineers look at this, or go with managing this yourself by deleting nodes manually.

**Comment by jbornemann** [comment]
We currently have other prioritized issues that are being worked. We thus are unable to prioritize back-porting this this repository clean feature to v3.5. The quickest solution for you right now would be to delete /var/grabbit

**Comment by sansai2011** [comment]
@jbornemann created new PR please loot into this as your availability. 
Great-full if done ASAP.
