### ISSUE TITLE
Job failure after cleaning repository

### ISSUE THREAD

**Issue by bsaylor** [TWCable/grabbit#181]
There is a problem occurring that causes jobs to fail to instantiate after partially cleaning a repository.  This happens when the repository has cleaned the low numbered (oldest) jobInstances (starting at 1), but there are still higher numbered jobInstances and the new transaction would cause jobInstances to collide with those pre-existing jobInstances.

**Exceptions**
```
PUT /grabbit/job HTTP/1.1] com.twcable.grabbit.client.services.impl.DefaultClientService Error while requesting a content sync for current Path: [/etc/xxx/yyy]
java.lang.reflect.UndeclaredThrowableException: null
org.apache.sling.api.resource.PersistenceException: Unable to create node at /var/grabbit/job/repository/jobInstances/6
```

**Steps to Reproduce**
1. Starting with a clean job repository, run a transaction with 5 paths. (you now have jobInstances 1-5).
2. Wait 60 minutes and run a second job with 5 paths. (You now have jobInstances 1-10).
3. Run the clean repository job with hours=1.  This will remove the first 5 jobInstances that are over 1 hour old and leave the second set of jobInstances that are less than 1 hour old. (You now have jobInstances 6-10).
4. Run a third transaction with 10 paths.  This transaction will fail when it tries to create jobInstance 6 which will collide with the existing jobInstances in the repository.

**Comment by bsaylor** [comment]
This issue is occurring because within JcrGrabbitJobInstanceDao::getNextJobInstanceId(), the nextId is choose by getting the number of jobInstance children and adding 1.  This assumes that the jobInstance nodes start with 1 and are consecutive.  However, the cleaning function that removes old jobInstances does not reorder them.  So it is easily possible for the jobInstances to start at some higher value which then will causes a conflict.

**Comment by jbornemann** [comment]
Good catch @bsaylor.

**Comment by sagarsane** [comment]
Nice catch. Thanks @bsaylor !

**Comment by jbornemann** [comment]
fixed by https://github.com/TWCable/grabbit/pull/182
