### ISSUE TITLE
Hi Team, while creating a new job to sync content between two AEM 6.3 instances curl command is failing 

### ISSUE THREAD

**Issue by harish6959** [TWCable/grabbit#199]
Thanks for taking the time to fill out an issue! To help the community solve your issue, please provide answers to the following questions, along with supporting log and configuration files.

**What version of AEM are you running?**

**How do you produce the issue?**

**Does the issue occur consistently?** 

**Any additional details?**

**Comment by harish6959** [comment]
Adding more logs:

curl -v -X PUT --header 'Content-Type: text/plain' --data-binary @/opt/jpm/adobe/author1/config.json -u admin:admin http://localhost:14503/grabbit/job
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 14503 (#0)
* Server auth using Basic with user 'admin'
> PUT /grabbit/job HTTP/1.1
> Host: localhost:14503
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.53.1
> Accept: */*
> Content-Type: text/plain
> Content-Length: 1082
> Expect: 100-continue
>
< HTTP/1.1 409 Conflict
< Date: Wed, 31 Jan 2018 00:40:54 GMT
< X-Content-Type-Options: nosniff
< Set-Cookie: cq-authoring-mode=TOUCH;Path=/;Expires=Wed, 07-Feb-2018 00:40:54 GMT
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Content-Type: text/html; charset=UTF-8
< Connection: close
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
    <head><title>409 Conflict</title></head>
    <body>
        <h1>Conflict</h1>
        <p>Cannot serve request to /grabbit/job in org.apache.sling.jcr.webdav.impl.servlets.SimpleWebDavServlet</p>

        <h3>Request Progress:</h3>
<pre>
      0 TIMER_START{Request Processing}
      2 COMMENT timer_end format is {&lt;elapsed microseconds&gt;,&lt;timer name&gt;} &lt;optional message&gt;
      7 LOG Method=PUT, PathInfo=null
      9 TIMER_START{handleSecurity}
   1454 TIMER_END{1442,handleSecurity} authenticator org.apache.sling.auth.core.impl.SlingAuthenticator@e1b1b1a returns true
   1706 TIMER_START{ResourceResolution}
   1845 TIMER_END{136,ResourceResolution} URI=/grabbit/job resolves to Resource=JobResource, type=twcable:grabbit/job, path=/grabbit/job
   1858 LOG Resource Path Info: SlingRequestPathInfo: path=&apos;/grabbit/job&apos;, selectorString=&apos;null&apos;, extension=&apos;null&apos;, suffix=&apos;null&apos;
   1858 TIMER_START{ServletResolution}
   1863 TIMER_START{resolveServlet(/grabbit/job)}
   1887 TIMER_END{22,resolveServlet(/grabbit/job)} Using servlet org.apache.sling.jcr.webdav.impl.servlets.SimpleWebDavServlet
   1890 TIMER_END{31,ServletResolution} URI=/grabbit/job handled by Servlet=org.apache.sling.jcr.webdav.impl.servlets.SimpleWebDavServlet
   1899 LOG Applying Requestfilters
   1904 LOG Calling filter: com.adobe.granite.resourceresolverhelper.impl.ResourceResolverHelperImpl
   1912 LOG Calling filter: org.apache.sling.i18n.impl.I18NFilter
   1916 LOG Calling filter: com.adobe.granite.httpcache.impl.InnerCacheFilter
   1924 LOG Calling filter: org.apache.sling.rewriter.impl.RewriterFilter
   1928 LOG Calling filter: com.adobe.cq.mcm.campaign.servlets.CampaignCopyTracker
   1932 LOG Calling filter: com.adobe.cq.history.impl.HistoryRequestFilter
   2057 LOG Calling filter: com.day.cq.wcm.core.impl.WCMRequestFilter
   2069 LOG Calling filter: com.adobe.cq.wcm.core.components.internal.servlets.CoreFormHandlingServlet
   2073 LOG Calling filter: com.adobe.granite.optout.impl.OptOutFilter
   2080 LOG Calling filter: com.day.cq.wcm.foundation.forms.impl.FormsHandlingServlet
   2084 LOG Calling filter: com.adobe.cq.social.commons.cors.CORSAuthenticationFilter
   2088 LOG Calling filter: org.apache.sling.engine.impl.debug.RequestProgressTrackerLogFilter
   2091 LOG Calling filter: com.day.cq.wcm.mobile.core.impl.redirect.RedirectFilter
   2096 LOG Calling filter: com.day.cq.wcm.core.impl.AuthoringUIModeServiceImpl
   2572 LOG Calling filter: org.apache.sling.security.impl.ContentDispositionFilter
   2578 LOG Calling filter: com.adobe.granite.csrf.impl.CSRFFilter
   2587 LOG Calling filter: com.adobe.granite.rest.assets.impl.AssetContentDispositionFilter
   2591 LOG Calling filter: com.adobe.granite.requests.logging.impl.RequestLoggerImpl
   2597 LOG Calling filter: com.adobe.granite.rest.impl.servlet.ApiResourceFilter
   2605 LOG Calling filter: com.day.cq.dam.core.impl.assetlinkshare.AdhocAssetShareAuthHandler
   2610 LOG Calling filter: com.adobe.cq.social.ugcbase.security.impl.SaferSlingPostServlet
   2613 LOG Calling filter: com.day.cq.wcm.core.impl.warp.TimeWarpFilter
   2624 LOG Applying Componentfilters
   2627 LOG Calling filter: com.day.cq.personalization.impl.TargetComponentFilter
   2630 LOG Calling filter: com.day.cq.wcm.core.impl.WCMComponentFilter
   2804 LOG Calling filter: com.day.cq.wcm.core.impl.WCMDebugFilter
   2825 TIMER_START{org.apache.sling.jcr.webdav.impl.servlets.SimpleWebDavServlet#0}
   2989 LOG Applying Error filters
   2993 LOG Calling filter: org.apache.sling.i18n.impl.I18NFilter
   2996 LOG Calling filter: org.apache.sling.rewriter.impl.RewriterFilter
   3003 TIMER_START{handleError:status=409}
   3453 TIMER_END{447,handleError:status=409} Using handler /libs/sling/servlet/errorhandler/default.jsp
   5557 LOG Found processor for post processing ProcessorConfiguration: {contentTypes=[text/html], order=-1, active=true, valid=true, processErrorResponse=true, pipeline=(generator=Config(type=htmlparser, config={}), transformers=(Config(type=linkchecker, config={}), Config(type=mobile, config=JcrPropertyMap [node=Node[NodeDelegate{tree=/libs/cq/config/rewriter/default/transformer-mobile: { jcr:primaryType = nt:unstructured, component-optional = true}}], values={jcr:primaryType=nt:unstructured, component-optional=true}]), Config(type=mobiledebug, config=JcrPropertyMap [node=Node[NodeDelegate{tree=/libs/cq/config/rewriter/default/transformer-mobiledebug: { jcr:primaryType = nt:unstructured, component-optional = true}}], values={jcr:primaryType=nt:unstructured, component-optional=true}]), Config(type=contentsync, config=JcrPropertyMap [node=Node[NodeDelegate{tree=/libs/cq/config/rewriter/default/transformer-contentsync: { jcr:primaryType = nt:unstructured, component-optional = true}}], values={jcr:primaryType=nt:unstructured, component-optional=true}]), serializer=Config(type=htmlwriter, config={}))}
   5740 TIMER_END{5738,Request Processing} Dumping SlingRequestProgressTracker Entries
</pre>


        <hr>
        <address>ApacheSling/2.6 (jetty/9.2.19.v20160908, Java HotSpot(TM) 64-Bit Server VM 1.8.0_144, Linux 4.9.75-25.55.amzn1.x86_64 amd64)</address>
    </body>
</html>
* Closing connection 0

**Comment by sagarsane** [comment]
Closing as duplicate of #200.
