### ISSUE TITLE
Introduce a "deleteBeforeWrite" flag in Grabbit Configs

### ISSUE THREAD

**Issue by sagarsane** [TWCable/grabbit#20]
This flag will be per path in a grabbit configuration. If this flag is enabled for a particular path, then `that path will be deleted from the client before writing`.

The configuration can look something like this : 
```json
{
	"path" : "/content/someContent",
	"workflowConfigIds" :
	    [
	        "/etc/workflow/launcher/config/update_asset_mod",
	        "/etc/workflow/launcher/config/update_asset_create",
	        "/etc/workflow/launcher/config/dam_xmp_nested_writeback",
	        "/etc/workflow/launcher/config/dam_xmp_writeback"
	    ],
	 "deleteBeforeWrite" : true
}
```

cc: @jazeren1 @jdigger

**Comment by jazeren1** [comment]
@sagarsane can we assume that flag is optional?  Meaning if it's not there then we assume it's value is false?  (reason I ask this question is so that we don't have to update current filters to have this flag unless we want to.)

**Comment by sagarsane** [comment]
Yeah that should be easy to do.

**Comment by jdigger** [comment]
One thing to take into account: would #18 influence this? I don't think it would, but a destructive operation coming from the server is worth being aware of. (The overwrites are destructive too, which is why I don't think it's a big deal.) But when #17 is implemented maybe it should call-out that paths would be deleted?

**Comment by sagarsane** [comment]
Yeah I agree. For #18, it should definitely be explicit as to "what all will happen?" with the pre-defined job sets. And yeah along with that, #17 should also call that out.

**Comment by jdigger** [comment]
Just added #23 (exclude paths) which would also have implications on this...
