### ISSUE TITLE
Copy from one location to an entirely new structure

### ISSUE THREAD

**Issue by MatthewKinbaum** [TWCable/grabbit#205]
**What version of AEM are you running?**
I have the tool working in AEM 6.4 without issues.

**Any additional details?**
Due to the repository restructuring in AEM 6.4, I would like to know if it is possible to copy nodes from my source environment, to a completely new location in my destination environment.

For example: lets say i have the following job I want to run in my source environment:
`{
    "path": "/etc/tags/someTag"
}`

Now in my destination environment (which is running 6.4) Adobe moved the location where they are storing tags to:

> /content/cq:tags

I would like to know if there is a way I can specify the output path like so:
`{
    "path": "/etc/tags/someTag",
    "destinationPath": "/content/cq:tags/someTag
}`

**Comment by sagarsane** [comment]
Hi @MatthewKinbaum  -- unfortunately, changing the paths on the `Grabbit Destination` is not possible today. 

However, this would be a good enhancement to have; so contribution help for this feature would be very welcome! 😄 

Please reopen the issue if you have any more questions! 

Thanks!
