### ISSUE TITLE
Issue while building grabbit - Authentication required when getting bundle info

### ISSUE THREAD

**Issue by ricardo-mela** [TWCable/grabbit#27]
I am trying to install grabbit on my development environment, but it fails when trying to run the ':grabbit:checkBundleStatus' task.

Running gradlew with the --debug flag, I can see that the issue is related to the installer not being able to query http://localhost:4502/system/console/bundles.json for the bundle list.

Log reads as follows:

```
10:06:33.165 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Sending request: GET /system/console/bundles.json HTTP/1.1
10:06:33.165 [DEBUG] [org.apache.http.headers] >> GET /system/console/bundles.json HTTP/1.1
10:06:33.165 [DEBUG] [org.apache.http.headers] >> Authorization: Basic YWRtaW46YWRtaW4
10:06:33.165 [DEBUG] [org.apache.http.headers] >> Accept: application/json
10:06:33.165 [DEBUG] [org.apache.http.headers] >> Host: localhost:4502
10:06:33.165 [DEBUG] [org.apache.http.headers] >> Connection: Keep-Alive
10:06:33.165 [DEBUG] [org.apache.http.headers] >> User-Agent: Apache-HttpClient/4.1.2 (java 1.5)
10:06:33.167 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Receiving response: HTTP/1.1 401 Unauthorized
10:06:33.167 [DEBUG] [org.apache.http.headers] << HTTP/1.1 401 Unauthorized
10:06:33.167 [DEBUG] [org.apache.http.headers] << Connection: Keep-Alive
10:06:33.167 [DEBUG] [org.apache.http.headers] << Server: Day-Servlet-Engine/4.1.52 
10:06:33.167 [DEBUG] [org.apache.http.headers] << Content-Length: 0
10:06:33.167 [DEBUG] [org.apache.http.headers] << Date: Thu, 30 Apr 2015 15:06:33 GMT
10:06:33.167 [DEBUG] [org.apache.http.headers] << WWW-Authenticate: Basic realm="OSGi Management Console"
10:06:33.167 [DEBUG] [org.apache.http.client.protocol.ResponseAuthCache] Caching 'basic' auth scheme for http://localhost:4502
10:06:33.167 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Connection can be kept alive indefinitely
10:06:33.167 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Target requested authentication
10:06:33.167 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Authorization challenge processed
10:06:33.167 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Authentication scope: BASIC 'OSGi Management Console'@localhost:4502
10:06:33.167 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Authentication failed
```
It seems that the installer is trying to get the bundle list but it can't because it needs authentication.

I grepped around in the source code but didn't find any reference to the task, to be able to change it and add the proper credentials.

I wonder if this is a real bug/enhancement, or if it is just an issue I am having. In any case, I hope you can help me out.

I can hand over additional environment info if need be.

Ricardo

**Comment by sagarsane** [comment]
Hey @ricardo-mela,

Thanks for the details in the logs. Can you let us know if your are using the default authentication for your instance or do you have different authentication credentials.

If you have different authentication credentials, it looks like the error may be happening in [cq-gradle-plugin](https://github.com/TWCable/cq-gradle-plugin) project.

The case probably is that by default the gradle-plugins uses default CQ authentication to connect to the instance. There is however a way to override that in your build file if you have different authentication. I believe you will find more information about that in the documentation : https://github.com/TWCable/cq-gradle-plugin/blob/master/README.md#configuration

adding @jdigger @jazeren1

**Comment by ricardo-mela** [comment]
Thanks @sagarsane , you just gave me the hint I was looking for. That did the trick :) I will use that config file to automate builds as well.

Thanks again, I hope I can be of help in the future.

Ricardo

**Comment by sagarsane** [comment]
Ok great thanks @ricardo-mela !
