### ISSUE TITLE
Grabbit fails to push content when using workflowConfigs for nodes without workflow

### ISSUE THREAD

**Issue by jbyrnessnip** [TWCable/grabbit#36]
When using workflowConfigIds with AEM 6.1, it appears the data transfer will fail if the node does not actually have workflow tied to it (typically a publish instance), with the error:

24.06.2015 12:34:23.999 *ERROR* [clientJobLauncherTaskExecutor-7] org.springframework.batch.core.step.AbstractStep Encountered an error executing step clientWorkflowOn in job clientJob
java.lang.IllegalStateException: launcherConfig Map value for /etc/workflow/launcher/config/dam_xmp_writeback cannot be null
        at com.twcable.grabbit.client.batch.workflows.impl.DefaultWorkFlowManager$_turnOn_closure2.doCall(DefaultWorkFlowManager.groovy:90)

Example config:

        {
                "path" : "/content/dam/VirtualAssistant",
                "workflowConfigIds" :
                [
                        "/etc/workflow/launcher/config/update_asset_mod",
                        "/etc/workflow/launcher/config/update_asset_create",
                        "/etc/workflow/launcher/config/dam_xmp_nested_writeback",
                        "/etc/workflow/launcher/config/dam_xmp_writeback"
                ]
        },

**Comment by jbornemann** [comment]
This is probably related to some of the concurrency issues we have been seeing around the workflow manager, that we are currently working on via #97 . Thanks for the ticket! @jbyrnessnip reopen this ticket the issue continues, and if you feel inclined :)
