### ISSUE TITLE
Add protocol buffers dependency to travis-ci

### ISSUE THREAD

**Issue by sagarsane** [TWCable/grabbit#5]
Currently, travis-ci does not understand `protoc` compiler and hence cannot build the project. Look into [adding dependencies to travis-ci](http://docs.travis-ci.com/user/installing-dependencies/).

**Comment by sagarsane** [comment]
Another useful link : https://christiankerl.wordpress.com/2012/02/03/setting-up-travis/

**Comment by jdigger** [comment]
Fixed with #37
