### ISSUE TITLE
Protected user/group properties

### ISSUE THREAD

**Issue by jdigger** [TWCable/grabbit#65]
Running against `/home` complains about mandatory property `"rep:principalName"` being missing.

Users/groups are being stored in Authorizable nodes. Even though both sides are running as "admin", `theSession().save()` in `JcrNodesWriter` gives errors like: `javax.jcr.nodetype.ConstraintViolationException: OakConstraint0021: /home/groups/b[[rep:Group]]: Mandatory property rep:principalName not found in a new node`

The issue is that this is a protected property in CRX 2.4 / JCR so the JCR API can not be used. (c.f. [Interaction With Protected Properties](http://www.day.com/specs/jcr/2.0/16_Access_Control_Management.html#16.3.12%20Interaction%20with%20Protected%20Properties), [Repository Model - Protected](http://www.day.com/specs/jcr/2.0/3_Repository_Model.html#3.7.2.2%20Protected).)

Before writing we need to check if the node type to be written is a user/group and use [Jackrabbit's UserManager API](http://docs.adobe.com/docs/de/aem/6-0/develop/ref/javadoc/org/apache/jackrabbit/api/security/user/UserManager.html) to create the node.
(see `com.twcable.grabbit.client.batch.steps.jcrnodes.JcrNodesWriter` in Grabbit.)

**Comment by dzmitry-kankalovich** [comment]
Just was passing by this issue. Could be the reason: https://blogs.perficientdigital.com/2019/01/15/including-service-users-in-your-aem-package/
