### ISSUE TITLE
Add better context to error logging

### ISSUE THREAD

**Issue by jdigger** [TWCable/grabbit#66]
For example, currently an error message looks like this:
```
01.09.2015 21:39:59.542 *ERROR* [10.143.18.200 [1441143599540] GET /grabbit/job HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught Throwable javax.jcr.PathNotFoundException: /content/dam/VirtualAssistant
	at org.apache.jackrabbit.core.ItemManager.getNode(ItemManager.java:577)
	at org.apache.jackrabbit.core.session.SessionItemOperation$6.perform(SessionItemOperation.java:129)
```

The problem is, there's no (reasonable) way to know what job caused that, especially when there's lots of jobs and multiple clients.

We should `try / catch` to add better context information such as the job id, possibly the IP of the client, etc.

**Comment by sagarsane** [comment]
Looks like this is on the Grabbit Server; we also have `batch-server.log` (and `batch-client`, which may be we should re-think if they should exist / what their scope should be) that logs few more details about the jobs. I am not sure about this error; but there may be more information logged in there.

**Comment by jdigger** [comment]
I was not aware that information was being logged there. It's certainly not in the docs...

**Comment by sagarsane** [comment]
Opened a PR for README update #67

**Comment by jbornemann** [comment]
@sagarsane @jdigger do you think there is more to do here?
