### ISSUE TITLE
Does Grabbit support copying Version history?

### ISSUE THREAD

**Issue by davidjgonzalez** [TWCable/grabbit#74]
Does Grabbit support copying Version history?

**Comment by jbornemann** [comment]
Not automatically, or in any sort of implicit way.  In general, we preserve weak/strong references; but don't yet have functionality to follow, and sync mix:referenceables.  

What is your use case?

**Comment by jdigger** [comment]
We closed this since we haven't heard back in a while. We're trying to keep the list trimmed to better focus our attention. If you would like to resume this conversation, please re-open. Thanks!
