### ISSUE TITLE
OutOfMemoryError (VM limit exceeded)

### ISSUE THREAD

**Issue by ogebert** [TWCable/grabbit#76]
We are trying to copy content from an AEM 6.0 author instance to a new AEM 6.1 author instance using grabbit 3.0 on the "old" author and 4.0.x on the new author. Both instances run with Java 1.7.
The old author throws OutOfMemoryErrors when assets (mostly zips and videos) > 200MB are processed.
As there is a max array index, more heap space will not solve the problem, I guess.

11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.core.step.tasklet.TaskletStep Applying contribution: [StepContribution: read=100, written=0, filtered=29, readSkips=0, writeSkips=0, processSkips=0, exitStatus=EXECUTING]
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.core.step.tasklet.TaskletStep Rollback for Error: java.lang.OutOfMemoryError: Requested array size exceeds VM limit
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.transaction.support.TransactionTemplate Initiating transaction rollback on application exception
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.support.transaction.ResourcelessTransactionManager Initiating transaction rollback
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.support.transaction.ResourcelessTransactionManager Rolling back resourceless transaction on [org.springframework.batch.support.transaction.ResourcelessTransactionManager$ResourcelessTransaction@2c015cbe]
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.repeat.support.RepeatTemplate Handling exception: java.lang.OutOfMemoryError, caused by: java.lang.OutOfMemoryError: Requested array size exceeds VM limit
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.repeat.support.RepeatTemplate Handling fatal exception explicitly (rethrowing first of 1): java.lang.OutOfMemoryError: Requested array size exceeds VM limit
11.09.2015 10:42:50.743 *ERROR* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.core.step.AbstractStep Encountered an error executing step serverJcrNodes in job serverJob
java.lang.OutOfMemoryError: Requested array size exceeds VM limit

**Comment by sagarsane** [comment]
Hi @ogebert, this error seems to be happening on the Grabbit Server side. 

Can you check if there is any more information / stack-trace in your `batch-server.log` on the Grabbit server? (https://github.com/TWCable/grabbit#monitoring--validating-the-content-sync)

You can also turn on DEBUG for that log which will log a lot more information about what nodes Grabbit Server is sending over.

**Comment by ogebert** [comment]
Hi,

I have the complete 2.5GB log ;-) Here's what happened at that time on the server side:

11.09.2015 10:42:24.379 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] com.twcable.grabbit.server.batch.steps.jcrnodes.JcrNodesWriter Sending NodeProto : name: "/content/dam/common/sts/root/application-pages/windenergie-en/001/windenergie.zip/jcr:conten
t/renditions/cq5dam.web.1024.1024.jpeg"
properties {
  property {
    name: "jcr:primaryType"
    type: 7
    value {
      stringValue: "nt:file"
    }
  }
}
mandatoryChildNode {
  name: "/content/dam/common/sts/root/application-pages/windenergie-en/001/windenergie.zip/jcr:content/renditions/cq5dam.web.1024.1024.jpeg/jcr:content"
  properties {
    property {
      name: "jcr:primaryType"
      type: 7
      value {
        stringValue: "nt:resource"
      }
    }
    property {
      name: "jcr:lastModifiedBy"
      type: 1
      value {
        stringValue: "admin"
      }
    }
    property {
      name: "jcr:mimeType"
      type: 1
      value {
        stringValue: "image/jpeg"
      }
    }
    property {
      name: "jcr:data"
      type: 2
      value {
        bytesValue: "\377\330\377\340\000\020JFIF\000\001\002\000\000\001\000\001\000\000\377\333\000C\000\003\002\002\003\002\002\003\003\003\003\004\003\003\004\005\b\005\005\004\004\005\n\a\a\006\b\f\n\f\f\v\n\v\v\r\016\022\020\r\016\021\016\v\v\020\026\020\021\023\024
\025\025\025\f\017\027\030\026\024\030\022\024\025\024\377\333\000C\001\003\004\004\005\004\005\t\005\005\t\024\r\v\r\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\024\02
4\024\024\024\024\024\024\024\024\024\024\024\377\300\000\021\b\002X\001\376\003\001\"\000\002\021\001\003\021\001\377\304\000\037\000\000\001\005\001\001\001\001\001\001\000\000\000\000\000\000\000\000\001\002\003\004\005\006\a\b\t\n\v\377\304\000\265\020\000\002\001\003
\003\002\004\003\005\005\004\004\000\000\001}\001\002\003\000\004\021\005\022!1A\006\023Qa\a\"q\0242\201\221\241\b#B\261\301\025R\321\360$3br\202\t\n\026\027\030\031\032%&\'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz\203\204\205\206\207\210\211\212\222\223\224\225\226\227\

**** LOTS OF DATA GOES HERE ****


\321E\024\000QE\024\000QE\024\000QE\024\000QE\024\000QE\024\000QE\024\000QE\024\000QE\024\000QE\024\000QE\024\000QE\024\000QE\024\000QE\024\000QE\024\000QE\024\000QE\024\001\377\331"
      }
    }
  }
}

11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.core.step.tasklet.TaskletStep Applying contribution: [StepContribution: read=100, written=0, filtered=29, readSkips=0, writeSkips=0, processSkips=0, exitStatus=EXECUTING]
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.core.step.tasklet.TaskletStep Rollback for Error: java.lang.OutOfMemoryError: Requested array size exceeds VM limit
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.transaction.support.TransactionTemplate Initiating transaction rollback on application exception
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.support.transaction.ResourcelessTransactionManager Initiating transaction rollback
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.support.transaction.ResourcelessTransactionManager Rolling back resourceless transaction on [org.springframework.batch.support.transaction.ResourcelessTransactionManager$ResourcelessTransaction@2c015cbe]
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.repeat.support.RepeatTemplate Handling exception: java.lang.OutOfMemoryError, caused by: java.lang.OutOfMemoryError: Requested array size exceeds VM limit
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.repeat.support.RepeatTemplate Handling fatal exception explicitly (rethrowing first of 1): java.lang.OutOfMemoryError: Requested array size exceeds VM limit
11.09.2015 10:42:50.743 *ERROR* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.core.step.AbstractStep Encountered an error executing step serverJcrNodes in job serverJob
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.support.transaction.ResourcelessTransactionManager Creating new transaction with name [org.springframework.batch.core.repository.support.SimpleJobRepository.updateExecutionContext]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.support.transaction.ResourcelessTransactionManager Initiating transaction commit
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.support.transaction.ResourcelessTransactionManager Committing resourceless transaction on [org.springframework.batch.support.transaction.ResourcelessTransactionManager$ResourcelessTransaction@10021fab]
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.support.transaction.ResourcelessTransactionManager Creating new transaction with name [org.springframework.batch.core.repository.support.SimpleJobRepository.update]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.support.transaction.ResourcelessTransactionManager Initiating transaction commit
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.support.transaction.ResourcelessTransactionManager Committing resourceless transaction on [org.springframework.batch.support.transaction.ResourcelessTransactionManager$ResourcelessTransaction@208f85f9]
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.core.step.AbstractStep Step execution complete: StepExecution: id=24, version=2, name=serverJcrNodes, status=FAILED, exitStatus=FAILED, readCount=100, filterCount=29, writeCount=0 readSkipCount=0, writeSkipCount=0, processSkipCount=0, commitCount=0, rollbackCount=1
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.support.transaction.ResourcelessTransactionManager Creating new transaction with name [org.springframework.batch.core.repository.support.SimpleJobRepository.updateExecutionContext]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.support.transaction.ResourcelessTransactionManager Initiating transaction commit
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.support.transaction.ResourcelessTransactionManager Committing resourceless transaction on [org.springframework.batch.support.transaction.ResourcelessTransactionManager$ResourcelessTransaction@3de5f91a]
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.core.job.flow.support.SimpleFlow Completed state=serverJob.serverJcrNodes with status=FAILED
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.core.job.flow.support.SimpleFlow Handling state=serverJob.fail7
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.core.job.flow.support.SimpleFlow Completed state=serverJob.fail7 with status=FAILED
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.core.job.AbstractJob Job execution complete: JobExecution: id=11, version=1, startTime=Fri Sep 11 10:42:17 CEST 2015, endTime=null, lastUpdated=Fri Sep 11 10:42:17 CEST 2015, status=FAILED, exitStatus=exitCode=FAILED;exitDescription=, job=[JobInstance: id=11, version=0, Job=[serverJob]], jobParameters=[{timestamp=1441960937749, path=/content/dam/common/sts/root/application-pages/windenergie-en, excludePaths=, contentAfterDate=null}]
11.09.2015 10:42:50.743 *INFO* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] com.twcable.grabbit.server.batch.ServerBatchJobExecutionListener Clearing ThreadLocal for current job: JobExecution: id=11, version=1, startTime=Fri Sep 11 10:42:17 CEST 2015, endTime=Fri Sep 11 10:42:50 CEST 2015, lastUpdated=Fri Sep 11 10:42:17 CEST 2015, status=FAILED, exitStatus=exitCode=FAILED;exitDescription=, job=[JobInstance: id=11, version=0, Job=[serverJob]], jobParameters=[{timestamp=1441960937749, path=/content/dam/common/sts/root/application-pages/windenergie-en, excludePaths=, contentAfterDate=null}] . Job Complete
11.09.2015 10:42:50.743 *INFO* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] com.twcable.grabbit.server.batch.ServerBatchJobExecutionListener Content sent for /content/dam/common/sts/root/application-pages/windenergie-en took : 32994 milliseconds


11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.support.transaction.ResourcelessTransactionManager Creating new transaction with name [org.springframework.batch.core.repository.support.SimpleJobRepository.update]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.support.transaction.ResourcelessTransactionManager Initiating transaction commit
11.09.2015 10:42:50.743 *DEBUG* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.support.transaction.ResourcelessTransactionManager Committing resourceless transaction on [org.springframework.batch.support.transaction.ResourcelessTransactionManager$ResourcelessTransaction@1a937324]
11.09.2015 10:42:50.743 *INFO* [54.77.235.255 [1441960937546] GET /grabbit/job HTTP/1.1] org.springframework.batch.core.launch.support.SimpleJobLauncher Job: [FlowJob: [name=serverJob]] completed with the following parameters: [{timestamp=1441960937749, path=/content/dam/common/sts/root/application-pages/windenergie-en, excludePaths=, contentAfterDate=null}] and the following status: [FAILED]

When I try to fetch only the rendition cq5dam.web.1024.1024.jpeg everything works fine, when I try to fetch the rendition "original" (what is the zip file itself), I get the same error.
Other zip files with less than 200 MB total size work fine.

**Comment by sagarsane** [comment]
Thanks @ogebert. Hmm that's odd. You mentioned that you are running on Java 1.7; but was wondering if you are running on 32bit OS or 64bit OS? 

Also, what is the max heap size allocated to CQ? I still think the issue is with too little heap space. Have you already tried increasing the heap space?

**Comment by ogebert** [comment]
Hi @sagarsane. It's a Windows 2008 R2 enterprise server (64-bit), with 80GB RAM. The AEM JVM runs with 16GB heap and when we did the tests there was nobody else working on the instance.
As we never experienced any memory problems in daily business, 16GB should be sufficient..?

**Comment by ogebert** [comment]
Sorry... hit the wrong button...

**Comment by sagarsane** [comment]
Oh. Yes 16gb should be enough I think.

So I tried to reproduce the issue on my dev machine but was unable to get this exception (I uploaded a 200+ MB asset and was trying to use that). I did however get the `Java heap space` exception on the server but not the one you got.

I suspect the issue is going to be similar to #2 as that issue also deals with Server going out of memory. (also see : https://github.com/TWCable/grabbit/issues/2#issuecomment-142782142)

One option right now to bypass this issue is to use the `excludePaths` feature in Grabbit to exclude the asset that is very large / the folder that contains very large assets. 

Of-course this isn't going to be permanent solution, but until #2 can be worked on..

**Comment by ogebert** [comment]
Ok thanks a lot for investigating. 

I understand that fixing this issue won't be easy and will take some time.

Unfortunately our customer's repository is around 1TB and holds more than 40,000 assets, lots of them with a size from 200 - 2000 MB - so excluding all the big files is not an option.
As we are also changing from SAN to S3 storage, we cannot simply copy the data on filesystem level, so we have to deal with vault-rcp for now I fear.

**Comment by jbornemann** [comment]
Just curious, what was the size of the original zip?  

Much to your point earlier, I don't think vertical memory is going to help here.  The protocol will currently allocate a buffer to accommodate the block being sent;  In your case, a large block, and according to the message maybe > byte[MaxInt - 5]. 

Unfortunately, this hits a wall.  The protocol is efficient at sending small lumps of data in a steam - nodes, small/medium dam assets.  We're still discussing a way accommodate situations like yours

**Comment by ogebert** [comment]
Yes, that's what I feared when I read the error message...
The zip had around 450MB but according to colleagues the same behaviour has also been noticed with video files that were not packaged. But there also we had file sizes > 300MB.

**Comment by jbornemann** [comment]
Hi @ogebert ! I hope we were able to help in some way! We are going to go ahead and close out this ticket as apart of some issue backlog housecleaning today! If you have further questions, or issues; feel free to reopen this ticket, or create another
