### ISSUE TITLE
Double check the Workflow Task done by Grabbit

### ISSUE THREAD

**Issue by jazeren1** [TWCable/grabbit#8]
Grabbit currently manages workflow launcher configs for paths that include DAM content. It turns off the asked workflow launcher configs before writing DAM content to the client and turns them back on at the end.
Adobe (http://docs.adobe.com/docs/en/cq/current/dam/managing_digitalassets.html#PackagingAssets) and other resources online resources (http://aemtips.blogspot.com/2013/05/how-to-migrate-huge-number-of-assets.html) recommend to ONLY turn off a couple of WorkflowLauncher bundles before writing DAM content.
Investigate if this is all we need and fix the Grabbit job correspondingly.

**Comment by sagarsane** [comment]
@jbornemann we can close this now right? (In lieu of https://github.com/TWCable/grabbit/commit/e72171c66af08d9b49eea0e03aa065bd39c484f8) ?

**Comment by jbornemann** [comment]
@sagarsane Yeah, I think so, however https://github.com/TWCable/grabbit/issues/12 definitely still needs to be addressed

**Comment by sagarsane** [comment]
Cool. Sounds good.

Sagar Sane
Software Engineer II / Tech Lead at iCiDIGITAL
MS in Computer Networking (CNC), N.C. State University
My GitHub Page <https://www.github.com/sagarsane>
Online Portfolio <https://sites.google.com/site/sagar2217/>
