### ISSUE TITLE
AEM 5.6.1 not able to build Grabbit 4.0.0

### ISSUE THREAD

**Issue by nabello** [TWCable/grabbit#81]
Hi, I'm trying to install Grabbit on a AEM 5.6.1 instance but I ran into a couple of issues. These are the steps that I try to follow:

1. Install a Fragment Bundle once per instance. (Worked great)

2. brew install protobuf241 (Worked great)

3. brew link --force --overwrite protobuf241 (Worked great)

4. Go to http://localhost:4502/system/console/bundles (Worked great)

5. Search for workflow-console and expand bundle when found. Notice Bundle Location and copy the path after jcrinstall: (/libs/cq/platform/install/cq-workflow-console-5.8.2.jar) (Only found cq-workflow-console-5.6.6.jar so used that instead of cq-workflow-console-5.8.2.jar)

6. From the top project directory executed : 
curl -u admin:admin -o cq-workflow-console-5.6.6.jar "http://localhost:4502/crx/de/download.jsp?path=/libs/cq/platform/install/cq-workflow-console-5.6.6.jar/jcr:content/jcr:data". 

7. Changed the gradle.properties to reflect the cq-workflow-console-5.6.6.jar and not cq-workflow-console-5.8.2.jar

8. gradlew clean build install refreshAllBundles (Build Success)

9. When I reload my AEM 5.6.1 instance I just built to, the instance no longer works, the error.log is riddled with ERRORs.

10. Restart AEM 5.6.1 instance, the instance can no longer restart, error.log has a lot of ERRORs.

Any thoughts ? Does Grabbit version 4.0.0 not support AEM 5.6.1 ? Should I try building without cq-workflow-console-5.x.x.jar or should I try building with cq-workflow-console-5.8.2.jar ? A little confused here any help would be great, thanks.

Best,
Nicola

**Comment by jbornemann** [comment]
Hi Nicola!

Use the latest version of Grabbit 3.0 for 5.6 instances.  Also, per the README.md, the cq workflow step isn't necessary for 5.6

Hope this helps!

**Comment by jbornemann** [comment]
@nabello does this resolve your issue?

**Comment by jdigger** [comment]
Per the README, the easiest thing to do is to simply install the prebuilt package available on Bintray: https://bintray.com/twcable/aem/Grabbit/view  (and, as Jeff said, you'd want the 3.x line)

**Comment by jdigger** [comment]
Closing this because it appears to be resolved. Please re-open if there's still a question.
