### ISSUE TITLE
deltaContent functionality at overall config level instead of path level

### ISSUE THREAD

**Issue by egenz** [TWCable/grabbit#86]
deltaContent is set by overall configuration in the json file instead of on a path-by-path basis. We'd like to specify which paths are using this setting instead of the entire sync.

**Comment by jdigger** [comment]
To both not break existing config and give a nice feature, I propose that the global delta flag stay, but it gets "applied" to each of the paths unless a path overrides it.

That way if you want delta for 90% of your paths but not one or two (or vice versa), you can do so easily.
