### ISSUE TITLE
Refactor JcrNodesProcessor to eliminate giant switch

### ISSUE THREAD

**Issue by jazeren1** [TWCable/grabbit#9]
Method of interest :
Server: JcrNodesProcessor#toProperty()

**Comment by Shashi-Bhushan** [comment]
Hello @jazeren1 , this method does not exist in JcrNodesProcessor class. could you update the description if this issue still exists.

**Comment by viveksachdeva** [comment]
@Shashi-Bhushan : This has been done as part of https://github.com/TWCable/grabbit/pull/133.. I think this ticket can be closed..
@jbornemann @sagarsane @jdigger

**Comment by sagarsane** [comment]
That is correct.

Fixed in #133
