### ISSUE TITLE
Add A Status Endpoint

### ISSUE THREAD

**Issue by jbornemann** [TWCable/grabbit#95]
e.g "/grabbit/status"

Would be an explicit channel for information commonly needed by clients.  Some simple, but extremely useful information :

  - Grabbit is installed, with version
  - Jobs completed/failed/in-progress in the last hour, with status
  - Lifetime jobs completed/failed/in-progress with status
  - maybe more now, or in the future

**Comment by jdigger** [comment]
The "Grabbit is installed w/ version" is handled by Sling.

For example,

```bash
curl -u admin:admin http://localhost:4502/system/console/bundles/com.twcable.grabbit.json | jq '.data[0].version'
```

For the other items, they would fall out naturally as part of #22

**Comment by jbornemann** [comment]
Ah, agreed. I'll close this out
